//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rengoku_sAttackSpreadSheet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rengoku_sAttackSpreadSheet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following motion values are the numbers at Critical Distance (the distance at which great damage can be dealt). Critical Distance will be described later.
        ///
        ///Shoot (R2): 8
        ///
        ///Charge I (Hold and release R2): 10 + 10
        ///
        ///Charge II (Hold R2 longer than Charge I): 11 + 11 + 11
        ///
        ///Quick Shot (O): 6 + 6 + 6
        ///
        ///Charge Step Power Shot (L2 + X after O): 13 + 13 + 13 + 13 + 13
        ///
        ///Diving Melee Attack (Triangle after Charge Step L2 + X): 35
        ///
        ///Jump Melee Attack (Triangle while jumping): 5
        ///
        ///High-Angle Shot (O after [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BowMV {
            get {
                return ResourceManager.GetString("BowMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword: Rising Slash (Triangle): 12 (4U: 14)
        ///
        ///Sword: Return Stroke (Triangle &gt; Triangle): 15 (4U: 17)
        ///
        ///Sword: Roundslash (Triangle &gt; Triangle &gt; Triangle): 28 (4U: 30)
        ///
        ///Sword: Dash Slash (Triangle + O): 20 (4U: 22)
        ///
        ///Sword: Charged Single Slash (O): 13 (4U: 16)
        ///
        ///Sword: Charged Double Slash (Hold and release O): 28 + 19 (4U: 30 + 20)
        ///
        ///Sword: Shield Attack (Triangle + O mid-combo): 13 + 9 (4U: 8 + 12)
        ///
        ///Sword: High Pressure Element Slash (Hold Triangle while charging during Element Enhancement): 75        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ChargeBladeMV {
            get {
                return ResourceManager.GetString("ChargeBladeMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mhworld.kiranico.com/skill
        ///https://monsterhunterworld.wiki.fextralife.com/Skills
        ///https://www.reddit.com/r/MonsterHunter/comments/7v0pp3/mhworld_motion_values_compiled/
        ///https://www.reddit.com/r/MonsterHunter/comments/7k1ea9/true_attack_values_new_fake_raw_multipliers_from/.
        /// </summary>
        public static string DataSources {
            get {
                return ResourceManager.GetString("DataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Slash (Triangle): 9 + 10
        ///
        ///Double Slash Return (Triangle &gt; Triangle): 10 + 10
        ///
        ///Rotation Slash (Triangle &gt; Triangle &gt; Triangle): 10 + 11 + 11
        ///
        ///Draw Slash (O): 4 + 4 + 5 + 5
        ///
        ///Rising Slash (Triangle after Draw Slash): 9 (When Demonized, 9)
        ///
        ///Demonized Reverse Slash (Triangle when Demonized): 13
        ///
        ///Demonized Double Slash (Triangle &gt; Triangle when Demonized): 15 + 9
        ///
        ///Demonized 6-Step Slash (Triangle &gt; Triangle &gt; Triangle when Demonized): 10 + 10 + 10 + 10 + 16 + 16
        ///
        ///Demon Dance (Triangle + O w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DualSwordsMV {
            get {
                return ResourceManager.GetString("DualSwordsMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Slash (Triangle): 48
        ///
        ///Rising Slash (Triangle + O): 38
        ///
        ///Cleave (O): 26
        ///
        ///Tackle (Triangle while evading, O &gt; O, O while charging): 26
        ///
        ///Charge II Tackle (O while in a level II charge): 35
        ///
        ///Charge III Tackle (O while in a level III charge): 48
        ///
        ///Diving Cleave (O after Tackle): 71
        ///
        ///Diving Cleave (O after level II Tackle): 85
        ///
        ///Diving Cleave (O after level III Tackle): 110
        ///
        ///Side Strike (Triangle &gt; Triangle): 15
        ///
        ///Charge Slash I (long Triangle press): 48
        ///
        ///Charge Slash II (longer press t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreatSwordMV {
            get {
                return ResourceManager.GetString("GreatSwordMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Thrust I (Triangle): 24 (4U: 24)
        ///
        ///Mid Thrust II (Triangle &gt; Triangle): 24
        ///
        ///Mid Thrust III (Triangle &gt; Triangle &gt; Triangle): 24
        ///
        ///High Thrust I (R2 + Triangle): 18 (4U: 18)
        ///
        ///High Thrust II (R2 + Triangle &gt; Triangle): 18
        ///
        ///High Thrust III (R2 + Triangle &gt; Triangle &gt; Triangle): 18
        ///
        ///Rising Slash (Triangle + O): 30 (4U: 28)
        ///
        ///Dash Thrust (L^ + Triangle): 30 (4U: 30)
        ///
        ///Slam Attack (Triangle after Rising Slash or Dash Thrust): 48 (4U: 40)
        ///
        ///Cleave (Triangle after Slam Attack): 68
        ///
        ///Wyvern Stake C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GunlanceMV {
            get {
                return ResourceManager.GetString("GunlanceMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsheathe Attack (Triangle when sheathed): 20 (4U: 20)
        ///
        ///Return Swing (Triangle after Unsheathe Attack): 16
        ///
        ///Side Smash (L^ + Triangle): 15 (4U: 15)
        ///
        ///Ground Smash I (Triangle): 37 (4U: 42)
        ///
        ///Ground Smash II (Triangle &gt; Triangle): 22 (4U: 20)
        ///
        ///Upswing (Triangle &gt; Triangle &gt; Triangle): 86 (4U: 90)
        ///
        ///Aerial Unsheathe Attack (Triangle in the air): 36 (4U: 42)
        ///
        ///Aerial Attack (Charge Lv 1) (Long R2 press in the air): 62 (4U: 65)
        ///
        ///Aerial Attack (Charge Lv 2) (Longer R2 press in the air than Lv 1): 66  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HammerMV {
            get {
                return ResourceManager.GetString("HammerMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Wyvern Bullet
        ///
        ///-When fired: 9 + 9 + 11 + 11 + 13 + 13 + 14 + 14 + 16 + 16 + 19 * 40 hits
        ///
        ///-The damage increases as you continue to fire, and the maximum damage is reached by the 11th shot
        ///
        ///-50 shots can be fired
        ///
        ///-Critical Distance is 2-4 rolls away
        ///
        ///-Cooltime is 250 seconds
        ///
        ///Sniping Wyvern Bullet
        ///
        ///-20+20+43+43?
        ///
        ///-There are more hits when further away
        ///
        ///-Range is considerably longer than normal. Even when shot at the very end of the training stage, it connects
        ///
        ///-Cooltime is 90 seco [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeavyBowGunMV {
            get {
                return ResourceManager.GetString("HeavyBowGunMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Slam (Triangle): 27 (4U: 33)
        ///
        ///Left Slam (Triangle): 22 (4U: 30)
        ///
        ///Right Slam (O): 26 (4U: 30)
        ///
        ///Double Right Turn (O &gt; O): 15 + 13
        ///
        ///Backward Slam (Triangle + O): 35 (4U: 45)
        ///
        ///Superpound (L^ + Triangle + O): 15 + 40 (4U: 15 + 45)
        ///
        ///Jumping Slam (Triangle in the air): 19 (4U: 36)
        ///
        ///Aerial Recital (R2 in the air): 15
        ///
        ///Recital Attack I (R2): 31 + 28
        ///
        ///Recital Attack II (L^ + R2): 30 + 28
        ///
        ///Recital Attack III (L&lt;- + R2): 30 + 28
        ///
        ///Recital Attack IV (L-&gt; + R2): 30 + 28
        ///
        ///Recital Attack V ( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HuntingHornMV {
            get {
                return ResourceManager.GetString("HuntingHornMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrust (L^ + Triangle): 10 (4U: 15)
        ///
        ///Rising Slash (Triangle): 15 + 14 (4U: 26 + 20)
        ///
        ///Backward Sweep (Triangle &gt; Triangle): 18 (4U: 26)
        ///
        ///Double Slash (Triangle &gt; Triangle &gt; Triangle): 18 + 24 (4U: 18 + 24)
        ///
        ///Overhead Smash (L^ + O): 26 (4U: 28)
        ///
        ///Sweep (O): 23 (4U: 24)
        ///
        ///Slam (O &gt; O): 30 (4U: 30)
        ///
        ///Jumping Slash (Triangle in the air): 15 (4U: 24)
        ///
        ///Jumping Rush Slash (R2 + X &gt; O): 29
        ///
        ///Kinsect &quot;Target Mark&quot; (R2 mid-combo): 5 (4U: 10?)
        ///
        ///After Red Extract Acquired
        ///
        ///Thrust (Attack Up) (L^ + Tria [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsectGlaiveMV {
            get {
                return ResourceManager.GetString("InsectGlaiveMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsheathe Thrust (L + Triangle while unsheathed): 21
        ///
        ///Mid Thrust I (Triangle): 21 (4U: 27)
        ///
        ///Mid Thrust II (Triangle &gt; Triangle): 21 (4U: 20)
        ///
        ///Mid Thrust III (Triangle &gt; Triangle &gt; Triangle): 29 (4U: 27)
        ///
        ///High Thrust I (O): 23 (4U: 22)
        ///
        ///High Thrust II (O &gt; O): 23 (4U: 22)
        ///
        ///High Thrust III (O &gt; O &gt; O): 29 (4U: 27)
        ///
        ///Sweep I (Triangle + O): 21 (4U: 20)
        ///
        ///Sweep III (Triangle + O): 21 (4U: 20)
        ///
        ///Jumping Thrust (Triangle in the air): 32 (4U: 30)
        ///
        ///Guard Thrust (Triangle during Guard): 21 (4U: 20)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LanceMV {
            get {
                return ResourceManager.GetString("LanceMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LBG has some differences in its Critical Distance and effective ranges. The MVs are otherwise the same as HBG
        ///
        ///Detonating Wyvern Bullet
        ///
        ///-27 damage
        ///
        ///-Up to three can be placed simultaneously
        ///
        ///-It explodes 5 times, or disappears after 60 seconds
        ///
        ///-Cooltime is 60 seconds per shot
        ///
        ///Sniping Wyvern Bullet
        ///
        ///-20+20+43+43?
        ///
        ///-There are more hits when further away
        ///
        ///-Range is considerably longer than normal. Even when shot at the very end of the training stage, it connects
        ///
        ///-Cooltime is 90 seconds        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LightBowGunMV {
            get {
                return ResourceManager.GetString("LightBowGunMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Slash (L + Triangle): 25
        ///
        ///Vertical Slash (Triangle): 23
        ///
        ///Thrust (O): 13
        ///
        ///Rising Slash (Triangle after Thrust): 20
        ///
        ///Fade Slash (Triangle + O): 23
        ///
        ///Spirit Blade I (R2 with no Spirit Gauge): 15
        ///
        ///Spirit Blade I (R2 with Spirit Gauge): 27
        ///
        ///Spirit Blade II (R2 R2 with Spirit Gauge): 33
        ///
        ///Spirit Blade III (R2 after Spirit Blade II): 13 + 15 + 35
        ///
        ///Spirit Roundhouse (R2 after Spirit Blade III or Spirit Insight): 42
        ///
        ///Step Spirit Blade (R2 after Fade Slash or Left/Right Fade Slash): 30
        ///
        ///Spiri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LongSwordMV {
            get {
                return ResourceManager.GetString("LongSwordMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe: Side Slash (Triangle): 25 (4U: 23)
        ///
        ///Axe: Rising Slash (Triangle &gt; Triangle): 27 (4U: 28)
        ///
        ///Axe: Overhead Slash (Triangle &gt; Triangle &gt; Triangle): 43 (4U: 40)
        ///
        ///Axe: Step Slash (L^ + Triangle): 10 (4U: 19)
        ///
        ///Axe: Downward Slash (Lv + Triangle): 24
        ///
        ///Axe: Hack &apos;n Slash (O): 25 + 23 (4U: 24)
        ///
        ///Axe: Finishing Sweep (R2 during Hack &apos;n Slash): 23 + 71 + 36 (4U: 57)
        ///
        ///Axe: Morph Slash (R2): 36 (4U: 30)
        ///
        ///Axe: Jump Slash (Triangle while jumping): 40 (4U: 43)
        ///
        ///Axe: Jump Morph Slash (R2 while jumping): [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SwitchAxeMV {
            get {
                return ResourceManager.GetString("SwitchAxeMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rush Slash (Triangle + O): 19
        ///
        ///Downward Slash (Triangle): 15
        ///
        ///Side Slash (Triangle &gt; Triangle): 13
        ///
        ///Sword &amp; Shield Combo (Triangle &gt; Triangle &gt; Triangle): 11 + 20
        ///
        ///Horizontal Slash (O): 23
        ///
        ///Slash Return (O &gt; O): 21
        ///
        ///Rotating Slash (O &gt; O &gt; O): 25
        ///
        ///Shield Attack (L^ + O): 9
        ///
        ///Back Knuckle (L^ + O &gt; O): 16
        ///
        ///Hard Bash (L^ + O &gt; O &gt; O): 31
        ///
        ///Charge Slash (Lv + O): 30 (Shield) + 38
        ///
        ///Climbing Slash (automatic after Charge Slash): 34
        ///
        ///Jump Slash (Triangle in the air): 20
        ///
        ///Fall Bash (O after [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SwordShieldMV {
            get {
                return ResourceManager.GetString("SwordShieldMV", resourceCulture);
            }
        }
    }
}
